Write a test for compression selection
This test doesn't pass, since the logic is too simple right now.

--- FAIL: TestCompressionHandler_ChosesBestCompression (0.00s)
    --- FAIL: TestCompressionHandler_ChosesBestCompression/wildcard_accepts_first_accepted_encoding (0.00s)
    --- PASS: TestCompressionHandler_ChosesBestCompression/plain_encoding_string_is_accepted (0.00s)
    --- PASS: TestCompressionHandler_ChosesBestCompression/coding_with_zero_weight_is_not_chosen (0.00s)
    --- FAIL: TestCompressionHandler_ChosesBestCompression/spaces_around_coding_name_and_qvalue (0.00s)
    --- FAIL: TestCompressionHandler_ChosesBestCompression/list_of_weight_is_parsed (0.00s)
    --- FAIL: TestCompressionHandler_ChosesBestCompression/the_best_option_is_chosen (0.00s)
    --- FAIL: TestCompressionHandler_ChosesBestCompression/the_best_option_from_the_available_ones_is_chosen (0.00s)
    --- PASS: TestCompressionHandler_ChosesBestCompression/identity_is_the_best_option (0.00s)
    --- FAIL: TestCompressionHandler_ChosesBestCompression/wildcard_is_the_best_option (0.00s)
    --- FAIL: TestCompressionHandler_ChosesBestCompression/wildcard_is_the_best_but_all_available_options_have_explicit_weights (0.00s)

Signed-off-by: Oleg Zaytsev <mail@olegzaytsev.com>