Bump promci to latest to avoid deprecated actions/cache CI issue. (#16013)
Current main is broken due to:

```
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: 0c45773b623bea8c8e75f6c82b208c3cf94ea4f9`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
```

This is odd given `actions/cache: 0c45773b623bea8c8e75f6c82b208c3cf94ea4f9` has a comment of v4.0.2 (so not v1 and v2), trying 4.1.0.

https://github.com/prometheus/prometheus/actions/runs/13267052807/job/37037025130?pr=16011

Signed-off-by: bwplotka <bwplotka@gmail.com>