Remove CircleCI Windows tests as they are too flaky
Windows tests on CircleCI are constantly failing for a variety of reasons in a
flaky way, putting pain on anyone submitting PRs. Nobody seems to be addressing
this at the moment, we just ignore them or retry them until they succeed,
defeating their purpose. So I suggest removing the Windows tests completely
until someone wants to figure out why they are broken and fix them.

For reference, here's only some of the observed failures:

```
=== RUN   TestUpdateMissedEvalMetrics
    manager_test.go:1325:
          Error Trace:  C:\go\src\github.com\prometheus\prometheus\rules\manager_test.go:1325
                              C:\go\src\github.com\prometheus\prometheus\rules\manager_test.go:1329
          Error:        Not equal:
                        expected: 2
                        actual  : 1
          Test:         TestUpdateMissedEvalMetrics

Signed-off-by: Julius Volz <julius.volz@gmail.com>
--- FAIL: TestUpdateMissedEvalMetrics (7.60s)
```

```
=== RUN   TestQueryStatistics/sum_by_(b)_(max_over_time(metricWith3SampleEvery10Seconds[60s]_@_30))
    engine_test.go:1217:
          Error Trace:  C:\go\src\github.com\prometheus\prometheus\promql\engine_test.go:1217
          Error:        Not equal:
                        expected: 8
                        actual  : 7
          Test:         TestQueryStatistics/sum_by_(b)_(max_over_time(metricWith3SampleEvery10Seconds[60s]_@_30))
          Messages:     Peak samples mismatch
--- FAIL: TestQueryStatistics/sum_by_(b)_(max_over_time(metricWith3SampleEvery10Seconds[60s]_@_30)) (0.00s)
```

```
=== RUN   TestNewHTTPCACert
    target_test.go:240: Get "https://127.0.0.1:50272": x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate "Prometheus Test CA")
2022/08/12 15:10:23 http: TLS handshake error from 127.0.0.1:50273: remote error: tls: bad certificate
--- FAIL: TestNewHTTPCACert (0.02s)
```

```
Too long with no output (exceeded 10m0s): context deadline exceeded
```

Signed-off-by: Julius Volz <julius.volz@gmail.com>