build(promtool): `url.JoinPath()` too new for current constraints
This replaces `url.JoinPath()` with a `fmt.Sprintf` modifier string,
since `prometheus` and `promtool` are currently built with go 1.18, and
`url.JoinPath()` was added in go 1.19:

https://tip.golang.org/doc/go1.19#minor_library_changes

Fixes:

```
>   promtool
go: downloading github.com/google/pprof v0.0.0-20230228050547-1710fef4ab10
cmd/promtool/main.go:857:57: url.JoinPath undefined (type *url.URL has no field or method JoinPath)
!! command failed: build -o /__w/prometheus/prometheus/promtool -ldflags -X github.com/prometheus/common/version.Version=2.42.0 -X github.com/prometheus/common/version.Revision=618162a45628036b9090a164a1257d82f97638a5 -X github.com/prometheus/common/version.Branch=HEAD -X github.com/prometheus/common/version.BuildUser=root@85985df2d31e -X github.com/prometheus/common/version.BuildDate=20230309-08:39:16  -extldflags '-static' -a -tags netgo,builtinassets github.com/prometheus/prometheus/cmd/promtool: exit status 2
make: *** [Makefile.common:198: common-build] Error 1
Error: Process completed with exit code 2.
```

https://github.com/prometheus/prometheus/actions/runs/4372548224/jobs/7649599532

Signed-off-by: TJ Hoplock <t.hoplock@gmail.com>